# Project Variables

Project_NAME ?= NutsAndBolts
ORG_NAME ?= NutsAndBolts
REPO_NAME ?= NutsAndBolts

.PHONY: migrations
migrations:
	cd ./NutsAndBolts.Data && dotnet ef --startup-project ../NutsAndBolts.web/ migrations add $(mname) && cd ..

.PHONY: db
db:
	cd ./NutsAndBolts.Data && dotnet ef --startup-project ../NutsAndBolts.web/ database update && cd ..

